---
title: "Supplementary Figures"
output: html_notebook
---

```{r}

library(dplyr)
library(ggplot2)
library(tidyr)
library(ggpubr)
library(stringr)
library(ggExtra)
library(colorBlindness)
library(cowplot)
library(ggrepel)
library(GGally)
library(RColorBrewer)


motif_colour<-"skyblue2"
flanking_colour<-"#773344"

non_syn_colour<- motif_colour 
stop_colour<-"#D81B60"
syn_colour<-"#ffc107"
wt_colour<-"#004D40"
hog1_colour<-"#e69ba8"
sho1_colour<-"#028b5b"

theme_sup_figure<-function(textsize=12){
  theme(axis.text = element_text(size = textsize, colour="black"),
        axis.title = element_text(size=textsize+5),
        legend.title = element_text(size=textsize+2),
        legend.text = element_text(size=textsize),
        text = element_text(colour = "black"))
}
```

```{r}
####Supp fig 1 - Surrounding region heatmap####

#T-test to see if Hog1 score for mutants is sig different from wt
supp_fig1_t_test<-read.csv("../../Data/DMS/results/codon_surrounding_region_DMS_scores.csv")%>%
  filter(condition == "MTX" & interactor == "Hog1" & sorbitol ==1)%>%
  filter(type !="WT" | position == 85)%>%                                        #Only 1 value for WT instead of 1 per position
  dplyr::mutate(identity=case_when(type %in% c("Non-Syn", "STOP") ~ paste(position, aa, sep="_"), #Separate Non-synonymous mutants,
                                   type %in% c("WT", "Syn") ~ "Syn+WT"))%>%          #WT and Syn mutants. the "reference" is WT+Syn pooled
  group_by(condition, interactor, sorbitol)%>%                                       #Group for T-test
  rstatix::pairwise_wilcox_test(log2FC ~ identity,                                   #Non-parametric t-test
                                ref.group = "Syn+WT",                                #Compare Non-syn mutants against Syn+WT   
                                p.adjust.method = "fdr",                             #Correction for multiple corrections
                                alternative ="two.sided")%>%                         #Two sided test                           
  rename(identity = group2)%>%                                                       #For joining later
  select(c(condition, interactor, sorbitol, identity, p.adj, p.adj.signif)) %>%      #Keep only relevant columns
  separate_wider_delim(., cols=identity, delim="_", names=c("position", "aa"))%>%
  mutate(position= as.numeric(position))%>%
  filter(p.adj.signif!="ns" & aa != "*")%>%
  select(position, aa)


supp_1_data<-read.csv("../../Data/DMS/results/codon_surrounding_region_DMS_scores.csv")%>%
  filter(condition == "MTX" & sorbitol ==1 & interactor== "Sho1")%>%
          group_by(position, target, condition, sorbitol, interactor, aa, strain_background, type) %>%
          summarize(replicates_per_aa = n(),
                    median_log2FC=median(log2FC, na.rm=T)) %>%
          filter(replicates_per_aa >= 2) %>%
          unite("identifier", target, condition, sorbitol, interactor, strain_background, remove=F)
  

supp_fig1_wt_pbs2<-read.csv("../../Data/DMS/reference/Pbs2_wt_seq.csv")%>%
  mutate(position=position+70)

supp_fig_1<-supp_1_data%>%
  ggplot(aes(x=as.factor(position), y=aa))+
  geom_tile(aes(fill=median_log2FC, colour=median_log2FC))+
  geom_text(data=supp_fig1_wt_pbs2, label="*")+
  geom_text(data=supp_fig1_t_test, label="H")+
  # geom_tile(data=supp_fig6_t_test, fill=NA, colour="black", linewidth=1)+
  scale_x_discrete(expand=c(0,0),breaks=seq(from=71, to=126, by=2) )+
  scale_y_discrete(expand = c(0,0))+
  scale_fill_gradient2(low="blue", mid="white", high="red")+
  scale_colour_gradient2(low="blue", mid="white", high="red", guide="none")+
  theme_sup_figure()+
  theme(panel.border = element_rect(fill = NA, colour="black"),
        panel.background = element_rect(fill="black"),
          panel.grid.major = element_blank())+
    labs(x="Position in Pbs2",
         y="Residue",
         fill="Sho1-Pbs2\nInteraction score")


supp_fig_1

save_plot(filename = "./Supplementary_figure_1.png", base_width = 12,  plot = supp_fig_1, dpi=300)

rm(supp_1_data, supp_fig1_wt_pbs2, supp_fig_1, supp_fig1_t_test)
```


```{r, message=F, warning=F}
####Supp fig 2 - Replicates####
###Panel A
sup_2_data<-read.csv("../../Data/DMS/results/codon_surrounding_region_DMS_scores.csv")

supp_2_panel_a<-sup_2_data%>%select(codon, position, condition, interactor, sorbitol, replicate, log2FC)%>%
  pivot_wider(names_from = replicate, values_from = log2FC)%>%
  ggpairs(columns = 6:ncol(.), mapping = aes(colour=interactor), upper = list(continuous = wrap("cor", size = 6, fontface="bold")))+
  ggplot2::scale_color_manual(values=c(hog1_colour, sho1_colour))+
  ggplot2::scale_fill_manual(values=c(hog1_colour, sho1_colour))+
  theme_bw()+
  theme_sup_figure()+
  labs(x="Interaction score",
       y="Interaction score")


###Panel B
sup_2_data_motif<-read.csv("../../Data/DMS/results/codon_extended_motif_DMS_scores.csv")

supp_2_panel_b<-sup_2_data_motif%>%arrange(replicate)%>%select(codon, position, condition, interactor, sorbitol, replicate, log2FC)%>%
  pivot_wider(names_from = replicate, values_from = log2FC)%>%
  ggpairs(columns = 6:ncol(.), mapping = aes(colour=interactor), upper = list(continuous = wrap("cor", size = 5, fontface="bold")))+
  ggplot2::scale_color_manual(values=c(hog1_colour, sho1_colour))+
  ggplot2::scale_fill_manual(values=c(hog1_colour, sho1_colour))+
  theme_bw()+
  theme_sup_figure()+
  labs(x="Interaction score",
       y="Interaction score")


###Panel C
sup_2_data_validation<-read.csv("../../Data/DMS/results/codon_validation_scores.csv")%>%
  mutate(interactor=case_when(interactor == "None" ~ "Proliferation",
                              TRUE ~ interactor))

supp_2_panel_c<-sup_2_data_validation%>%
  arrange(replicate)%>%
  select(codon, position, condition, interactor, sorbitol, replicate, log2FC)%>%
  pivot_wider(names_from = replicate, values_from = log2FC)%>%
  ggpairs(columns = 6:ncol(.), mapping = aes(colour=interactor), upper = list(continuous = wrap("cor", size = 4.5, fontface="bold")))+
  ggplot2::scale_color_manual(values=c(hog1_colour, "cornflowerblue", sho1_colour))+
  theme_bw()+
  theme_sup_figure()+
  labs(x="Interaction score",
       y="Interaction score")


###ASSEMBLY
supp_fig_2<-plot_grid(ggmatrix_gtable(supp_2_panel_a), 
                      ggmatrix_gtable(supp_2_panel_b), 
                      ggmatrix_gtable(supp_2_panel_c),
                      nrow=3, ncol=1, 
                      labels = "auto",
                      label_size = 20,
                      label_y = c(1.02, 1.02))



# supp_fig_2


save_plot(filename="Supplementary_figure_2.png", base_asp=0.9 , plot=supp_fig_2, base_height = 15)# , base_asp = 2.0

rm(sup_2_data, sup_2_data_motif, sup_2_data_validation, supp_2_panel_a, supp_2_panel_b, supp_2_panel_c, supp_fig_2)
```


```{r}
####Supp Fig 3 - Sho1 vs Hog1 ####

supp_3_data<-read.csv("../../Data/DMS/results/aa_surrounding_region_DMS_scores.csv")%>%
  filter(condition == "MTX" & sorbitol == 1)%>%
  mutate(motif=case_when(position %in% 85:100 ~ "motif",
                         TRUE ~ "non-motif"))




sho1_con_interval<-supp_3_data%>%
  select(position, interactor, aa, type, median_sel_coeff, median_log2FC, sd_log2FC, sd_sel_coeff, motif)%>%
  pivot_wider(names_from = interactor, values_from = c(median_sel_coeff, median_log2FC, sd_log2FC, sd_sel_coeff))%>%
  filter(type == "STOP")%>%
  pull(median_log2FC_Sho1)%>%
  quantile(probs=c(0.025, 0.975), names=F , na.rm=T)



hog1_con_interval<-supp_3_data%>%
  select(position, interactor, aa, type, median_sel_coeff, median_log2FC, sd_log2FC, sd_sel_coeff, motif)%>%
  pivot_wider(names_from = interactor, values_from = c(median_sel_coeff, median_log2FC, sd_log2FC, sd_sel_coeff))%>%
  filter(type == "STOP")%>%
  pull(median_log2FC_Hog1)%>%
  quantile(probs=c(0.025, 0.975), names=F, na.rm=T)



#Grey rectangles represent the 95% confidence interval of the mean of STOP codons
#Values under the 95% quantile of STOP are brought to 97,5 quantile of STOP (detection limit)
supp_fig_3<-supp_3_data %>%
  select(position, interactor, aa, type, median_sel_coeff, median_log2FC, sd_log2FC, sd_sel_coeff, motif)%>%
  pivot_wider(names_from = interactor, values_from = c(median_sel_coeff, median_log2FC, sd_log2FC, sd_sel_coeff))%>%
  filter(type != "STOP")%>%
  mutate(median_log2FC_Sho1 = case_when(median_log2FC_Sho1 < sho1_con_interval[2] ~ sho1_con_interval[2],
                                        TRUE ~ median_log2FC_Sho1),
         median_log2FC_Hog1 = case_when(median_log2FC_Hog1 < hog1_con_interval[2] ~ hog1_con_interval[2],
                                        TRUE ~ median_log2FC_Hog1))%>% #Bring values lower than conf int of STOP codons to limit of con int
  arrange(desc(motif))%>%
ggplot(aes(x=median_log2FC_Sho1, y=median_log2FC_Hog1))+
  geom_rect(xmin=sho1_con_interval[1], xmax=sho1_con_interval[2], ymin=-Inf, ymax=Inf, fill="grey90", colour="grey90")+
  geom_rect(xmin=-Inf, xmax=Inf, ymin=hog1_con_interval[1], ymax=hog1_con_interval[2], fill="grey90", colour="grey90")+
  scale_colour_manual(values = c(motif_colour, flanking_colour), labels=c("Extended Motif", "Flanking sequences"))+
  geom_point(aes(colour=motif))+
  geom_abline(intercept=0, slope=1, linetype="dashed")+
  theme_classic()+
  scale_x_continuous(limits =c(-3,3) )+
  scale_y_continuous(limits=c(-3, 3))+
  theme_sup_figure()+
  theme(legend.title = element_blank(),
       legend.position = c(0.25, 0.8),
       legend.background = element_rect(fill=NA, colour="black"),
       legend.text=element_text(size=10),
       )+
  labs(x="Sho1-Pbs2\nInteraction score",
       y="Hog1-Pbs2\nInteraction score")
  


supp_fig_3_density<-ggMarginal(supp_fig_3, type="density",  groupFill = T) #Add density plots in margins

supp_fig_3_density

save_plot(filename = "Supplementary_figure_3.png", plot=supp_fig_3_density)

rm(supp_3_data, sho1_con_interval, hog1_con_interval, supp_fig_3, supp_fig_3_density)
```


```{r}
####Supp fig 4 - Corr first/second screen ####

supp_fig4_prelim_data<-read.csv("../../Data/DMS/results/aa_surrounding_region_DMS_scores.csv")%>%
  rename(prelim_log2FC=median_log2FC)%>%
  mutate(position=position)
  
supp_fig4_motif_data<-read.csv("../../Data/DMS/results/aa_extended_motif_DMS_scores.csv")%>%
  rename(motif_log2FC=median_log2FC)

supp_fig4_data<-left_join(supp_fig4_motif_data, supp_fig4_prelim_data, by=c("position", "aa", "type", "condition", "interactor", "sorbitol", "target"))
  


supp_fig4<-supp_fig4_data%>%
  filter(condition == "MTX" & sorbitol==1 & interactor=="Sho1")%>%
ggplot(aes(x=prelim_log2FC, y=motif_log2FC))+
  geom_point(aes(group=interaction(position, aa)), shape=21, fill=motif_colour)+#
  stat_cor(method="spearman", cor.coef.name = "rho", size=5)+
  theme_classic()+
  theme_sup_figure()+
  labs(x="Sho1-Pbs2 Interaction score\n(Surrounding region)",
       y="Sho1-Pbs2 Interaction score\n(Extended motif)")

supp_fig4

save_plot(filename = "Supplementary_figure_4.png", plot = supp_fig4)

rm(supp_fig4_prelim_data, supp_fig4_motif_data, supp_fig4_data, supp_fig4)

```


```{r}
####Supp fig 5 - Destabilization ####

supp_fig5_data<-read.csv("../../Data/DMS/results/codon_extended_motif_DMS_scores.csv")%>%
  filter(condition == "MTX" & sorbitol ==1)%>%
          group_by(position, target, condition, sorbitol, interactor, aa, strain_background, type) %>%
          summarize(replicates_per_aa = n(),
                    median_log2FC=median(log2FC, na.rm=T)) %>%
          filter(replicates_per_aa >= 2) %>%
          unite("identifier", target, condition, sorbitol, interactor, strain_background, remove=F)

#T-test to see if Hog1 score for mutants is sig different from wt
supp_fig5_t_test<-read.csv("../../Data/DMS/results/codon_extended_motif_DMS_scores.csv")%>%
  filter(condition == "MTX" & interactor %in% c("Sho1", "Hog1") & sorbitol ==1)%>%
  filter(type !="WT" | position == 85)%>%                                        #Only 1 value for WT instead of 1 per position
  dplyr::mutate(identity=case_when(type %in% c("Non-Syn", "STOP") ~ paste(position, aa, sep="_"), #Separate Non-synonymous mutants,
                                   type %in% c("WT", "Syn") ~ "Syn+WT"))%>%          #WT and Syn mutants. the "reference" is WT+Syn pooled
  group_by(condition, interactor, sorbitol)%>%                                       #Group for T-test
  rstatix::pairwise_wilcox_test(log2FC ~ identity,                                   #Non-parametric t-test
                                ref.group = "Syn+WT",                                #Compare Non-syn mutants against Syn+WT   
                                p.adjust.method = "fdr",                             #Correction for multiple corrections
                                alternative ="two.sided")%>%                         #Two sided test                           
  rename(identity = group2, p.signif_log2FC=p.adj.signif, p.adj.log2FC=p.adj)%>%     #For joining later
  select(c(condition, interactor, sorbitol, identity, p.adj.log2FC, p.signif_log2FC)) %>%#Keep only relevant columns
  separate_wider_delim(., cols=identity, delim="_", names=c("position", "aa"))%>%
  mutate(position= as.numeric(position))

supp_fig5_data<-left_join(supp_fig5_data, supp_fig5_t_test, by=c("condition", "interactor", "sorbitol", "position", "aa"))%>%
  ungroup()%>%
  select(position, sorbitol, interactor, aa, type, median_log2FC, p.adj.log2FC, p.signif_log2FC)%>%
   replace_na(list(p.signif_log2FC="ns"))%>%
    pivot_wider(names_from = c(interactor, sorbitol), values_from = c(median_log2FC, p.adj.log2FC, p.signif_log2FC))%>%
filter(!(is.na(median_log2FC_Hog1_1)))


supp_fig5_data<-supp_fig5_data%>%
  mutate(Hog1_effect=case_when(type != "Non-Syn" ~ type,
                               type == "Non-Syn" & p.signif_log2FC_Hog1_1 != "ns" ~ "Non-Syn (Hog1 different)",
                               type == "Non-Syn" & p.signif_log2FC_Hog1_1 == "ns" ~ "Non-Syn (Hog1 not different)"))


supp_fig5<-supp_fig5_data%>%
  ggplot(aes(x=median_log2FC_Sho1_1, y=median_log2FC_Hog1_1, colour=Hog1_effect))+
  geom_point(aes(colour=Hog1_effect, group = interaction(aa, position)))+
  scale_colour_manual(values=c("#623CEA", motif_colour, stop_colour, syn_colour, wt_colour), labels=c("Missense (Effect\non Hog1 binding)", "Missense (No effect\non Hog1 binding)", "Nonsense", "Silent", "WT"))+
  theme_classic()+
  theme_sup_figure()+
  theme(legend.text = element_text(margin = margin(t=0.4, b=0.4, unit="line")))+
  labs(x="Sho1-Pbs2 Interaction score",
       y="Hog1-Pbs2 Interaction score",
       colour="Mutation type",
       shape="Hog1 effect")

supp_fig5


 save_plot(filename="./Supplementary_figure_5.png", plot = supp_fig5, dpi=300, base_asp = 2)

rm(supp_fig5, supp_fig5_data, supp_fig5_t_test)
```

```{r}
####Supp fig 6 - Extended motif heatmap####


#T-test to see if Hog1 score for mutants is sig different from wt
supp_fig6_t_test<-read.csv("../../Data/DMS/results/codon_extended_motif_DMS_scores.csv")%>%
  filter(condition == "MTX" & interactor == "Hog1" & sorbitol ==1)%>%
  filter(type !="WT" | position == 85)%>%                                        #Only 1 value for WT instead of 1 per position
  dplyr::mutate(identity=case_when(type %in% c("Non-Syn", "STOP") ~ paste(position, aa, sep="_"), #Separate Non-synonymous mutants,
                                   type %in% c("WT", "Syn") ~ "Syn+WT"))%>%          #WT and Syn mutants. the "reference" is WT+Syn pooled
  group_by(condition, interactor, sorbitol)%>%                                       #Group for T-test
  rstatix::pairwise_wilcox_test(log2FC ~ identity,                                   #Non-parametric t-test
                                ref.group = "Syn+WT",                                #Compare Non-syn mutants against Syn+WT   
                                p.adjust.method = "fdr",                             #Correction for multiple corrections
                                alternative ="two.sided")%>%                         #Two sided test                           
  rename(identity = group2)%>%                                                       #For joining later
  select(c(condition, interactor, sorbitol, identity, p.adj, p.adj.signif)) %>%      #Keep only relevant columns
  separate_wider_delim(., cols=identity, delim="_", names=c("position", "aa"))%>%
  mutate(position= as.numeric(position))%>%
  filter(p.adj.signif!="ns" & aa != "*")%>%
  select(position, aa)


supp_6_data<-read.csv("../../Data/DMS/results/codon_extended_motif_DMS_scores.csv")%>%
  filter(condition == "MTX" & sorbitol ==1 & interactor== "Sho1")%>%
          group_by(position, target, condition, sorbitol, interactor, aa, strain_background, type) %>%
          summarize(replicates_per_aa = n(),
                    median_log2FC=median(log2FC, na.rm=T)) %>%
          filter(replicates_per_aa >= 2) %>%
          unite("identifier", target, condition, sorbitol, interactor, strain_background, remove=F)
  

supp_fig6_wt_pbs2<-read.csv("../../Data/DMS/reference/Pbs2_wt_seq.csv")%>%
  mutate(position=position+70)%>%
  filter(position %in% 85:100)

supp_fig_6<-supp_6_data%>%
  ggplot(aes(x=as.factor(position), y=aa))+
  geom_tile(aes(fill=median_log2FC, colour=median_log2FC))+
  geom_text(data=supp_fig6_wt_pbs2, label="*")+
  geom_text(data=supp_fig6_t_test, label="H")+
  # geom_tile(data=supp_fig6_t_test, fill=NA, colour="black", linewidth=1)+
  scale_x_discrete(expand=c(0,0), )+
  scale_y_discrete(expand = c(0,0))+
  scale_fill_gradient2(low="blue", mid="white", high="red")+
  scale_colour_gradient2(low="blue", mid="white", high="red", guide="none")+
  theme_sup_figure()+
  theme(panel.border = element_rect(fill = NA, colour="black"),
        panel.background = element_rect(fill="black"),
          panel.grid.major = element_blank())+
    labs(x="Position in Pbs2",
         y="Residue",
         fill="Sho1-Pbs2\nInteraction score")


supp_fig_6

save_plot(filename = "./Supplementary_figure_6.png", base_width=8 ,plot=supp_fig_6, dpi=300)

rm(supp_6_data, supp_fig6_wt_pbs2, supp_fig_6)

```


```{r}

####Supp fig  7 - Effect of sorbitol####

supp_fig7_data<-read.csv("../../Data/DMs/results/aa_extended_motif_DMS_scores.csv")%>%
  filter(interactor =="Sho1" & condition == "MTX")%>%
  select(position, aa, sorbitol, type, median_log2FC)%>%
  pivot_wider(names_from = sorbitol, values_from = median_log2FC, names_prefix = "sorb_")


supp_fig7<-supp_fig7_data%>%
  ggplot(aes(x=sorb_1, y=sorb_0))+
  geom_point(aes(colour=type))+
  stat_cor(method="spearman", cor.coef.name = "rho", show.legend = F, size=6)+
  scale_colour_manual(values=c(motif_colour, stop_colour, syn_colour, wt_colour),labels=c("Missense", "Nonsense", "Silent", "WT"))+
  theme_classic()+
  theme_sup_figure()+
  labs(x="Sho1-Pbs2 Interaction score\nin 1 M sorbitol",
       y="Sho1-Pbs2 Interaction score\nin absence of sorbitol",
       colour="Mutation type")

supp_fig7

save_plot(filename="./Supplementary_figure_7.png", plot=supp_fig7, dpi=300)

rm(supp_fig7, supp_fig7_data)
```


```{r}

####Supp fig 8 - Validation####



# DMS data from the first DMS screen, larger region
supp_fig8_prelim_dms_data<-read.csv("../../Data/DMS/results/aa_surrounding_region_DMS_scores.csv")%>%
  filter(condition == "MTX" &  interactor == "Sho1")%>%
  select(median_log2FC, sd_log2FC, position, aa, sorbitol)%>%
  mutate(screen="Surrounding region")

#DMS data from second DMS screen on extended motif
supp_fig8_motif_dms_data<-read.csv("../../Data/DMS/results/aa_extended_motif_DMS_scores.csv")%>%
  filter(condition == "MTX" &  interactor == "Sho1")%>%
  select(median_log2FC, sd_log2FC, position, aa, sorbitol)%>%
  mutate(screen="Extended motif")

#combine DMS data
supp_fig8_dms_data<-rbind(supp_fig8_prelim_dms_data, supp_fig8_motif_dms_data)

#PANEL A - growth curves
supp_fig8a_gc_data<-read.csv("../../Data/growthcurves/results_validation_growth_curves.csv")

#Prepare growth curve data frame for joining with DMS data
supp_fig8a_gc_data<-supp_fig8a_gc_data%>%
  filter(mutation != "P94A+P97A")%>% #Not in DMS data, as it is a double mutant
  group_by(mutation, condition)%>%
  summarize(median_mtx_gr=median(mtx_gr, na.rm=T),
            sd_mtx_gr=sd(mtx_gr, na.rm=T),
            median_dmso_gr=median(dmso_gr, na.rm=T),
            sd_dmso_gr=sd(dmso_gr, na.rm=T))%>%
  ungroup%>%
  mutate(sorbitol=case_when(condition == "Sorbitol" ~ 1,
                            TRUE ~ 0))%>%
mutate(position=as.numeric(str_replace_all(mutation, "[:alpha:]", "")),
       aa=str_sub(mutation, start=-1))

#Combine DMS data and growth curve data
supp_fig8a_data<-left_join(supp_fig8a_gc_data, supp_fig8_dms_data, by=c("position", "aa", "sorbitol"))%>%
  drop_na("screen")


#Validation of fitness effects.
supp_fig8_panel_a<-supp_fig8a_data%>%
  mutate(sorbitol=as.character(sorbitol))%>%
  ggplot(aes(x=median_log2FC, y=median_mtx_gr, colour=sorbitol))+
    geom_point(aes(group=mutation))+
    scale_colour_viridis_d(option="plasma", labels=c("None", "1 M"), begin=0.25, end=0.75)+
    stat_cor(method="spearman", cor.coef.name = "rho", show.legend=F, size=5)+
  facet_wrap(~screen)+
    theme_classic()+
  theme_sup_figure()+
  theme(panel.background = element_rect(colour="black"),
        strip.text = element_text(size=17))+
    labs(x="DMS libraries Sho1-Pbs2 Interaction scores",
       y="Reconstructed mutants\nGrowth rate (OD/h)",
       colour="Sorbitol")

supp_fig8_panel_a

#Panel B - validation DHFR-PCA

supp_fig8b_validation<-read.csv("../../Data/DMS/results/aa_validation_scores.csv")

supp_fig8b_validation<-supp_fig8b_validation%>%
  filter(condition == "MTX" & interactor == "Sho1")%>%
  select(median_log2FC, position, aa, sorbitol)%>%
  rename(validation_median_log2FC=median_log2FC)

supp_fig8b_data<-inner_join(supp_fig8b_validation, supp_fig8_dms_data, by=c("aa", "position", "sorbitol"))


supp_fig8_panel_b<-supp_fig8b_data%>%
  mutate(sorbitol=as.character(sorbitol))%>%
  ggplot(aes(x=median_log2FC, y=validation_median_log2FC, colour=sorbitol))+
    geom_point(aes(group=interaction(aa, position)))+
    scale_colour_viridis_d(option="plasma", labels=c("None", "1 M"), begin=0.25, end=0.75)+
    stat_cor(method="spearman", cor.coef.name = "rho", show.legend=F, size=5)+
  facet_wrap(~screen)+
    theme_classic()+
  theme_sup_figure()+
  theme(panel.background = element_rect(colour="black"),
        strip.text = element_text(size=17))+
    labs(x="DMS libraries Sho1-Pbs2 Interaction scores",
       y="Reconstructed mutants\nSho1-Pbs2 Interaction score",
       colour="Sorbitol")

supp_fig8_panel_b


supp_fig8<-cowplot::plot_grid(supp_fig8_panel_a+theme(legend.text = element_text(size=17),
                                                      legend.title = element_text(size=20)), 
                              supp_fig8_panel_b+theme(legend.text = element_text(size=17),
                                                      legend.title = element_text(size=20)), 
                              nrow=2,ncol=1,
                              labels = "auto", label_colour = "black", label_size = 20)

supp_fig8

save_plot(filename = "./Supplementary_figure_8.png", supp_fig8, dpi=300, base_height = 8)


rm(supp_fig8, supp_fig8_dms_data, supp_fig8_motif_dms_data, supp_fig8_panel_a, supp_fig8_panel_b, supp_fig8_prelim_dms_data, supp_fig8a_data, supp_fig8a_gc_data, supp_fig8b_data, supp_fig8b_validation)
```



```{r}

####Supp fig 9 - Fitness effects ####


supp_fig9_data<-read.csv("../../Data/DMS/results/codon_validation_scores.csv")%>%
  filter(condition == "Stress")


supp_fig9_t_test<-supp_fig9_data%>%
  filter(condition == "Stress")%>%
  dplyr::mutate(t_test_type=case_when(type %in% c("Non-Syn", "STOP") ~ mutant, #Separate Non-syn mutants,
                                   type %in% c("WT", "Syn") ~ "Syn+WT"))%>%          #the "reference" is WT+Syn pooled
  group_by(sorbitol)%>%                                       #Group for T-test
  rstatix::pairwise_t_test(selection_coefficient ~ t_test_type,                                   #Non-parametric t-test
                                ref.group = "Syn+WT",                                #Compare Non-syn mutants against Syn+WT   
                                p.adjust.method = "fdr",                             #Correction for multiple corrections
                                alternative ="two.sided",                            #Two-sided t-test 
                           pool.sd=F,                                               #Welch's t-test
                           var.equal=F)%>%                         
  rename(mutant = group2, p.signif_sel_coeff=p.adj.signif, p.adj.sel_coeff=p.adj)


supp_fig9<-supp_fig9_data%>%
  filter(sorbitol ==1)%>%
  ggplot(aes(x=mutant, y=selection_coefficient))+
  geom_text(data=supp_fig9_t_test%>%filter(p.signif_sel_coeff != "ns" & sorbitol ==1), aes(x=mutant, y=0.1, label=p.signif_sel_coeff))+
  geom_boxplot(aes(fill=type), outlier.shape = 21, outlier.size = 0.75)+
  scale_fill_manual(values = c(motif_colour, stop_colour, syn_colour, wt_colour), labels=c("Missense", "Nonsense", "Silent", "WT"), name="Mutation type")+
  theme_bw()+
  theme_sup_figure()+
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5, 
                                   colour=c("black", "black", "red", rep("black", 58)),
                                   face=c("plain","plain", "bold", rep("plain", 58))))+
  labs(x="Pbs2 mutant",
       y="Selection coefficient")


supp_fig9

save_plot(filename = "Supplementary_figure_9.png", plot=supp_fig9, base_asp = 3)


# rm(supp_fig9_data, supp_fig9, supp_fig9_t_test)

```

```{r}
#### Supp fig 10 - Specificity volcano plot ####

supp_fig10_data<-read.csv("../../Data/Solid_PCA/results/solid_pca_results.csv")%>%
  filter(mutation != "WT")%>%
  mutate(mutation_sig=case_when(p.adj < 0.05 ~ mutation,
                                p.adj >= 0.05 ~ "Non-significant"))

supp_fig10_data$mutation_sig<-factor(supp_fig10_data$mutation_sig, levels=c("I87W","K85W","L98F","N92H","N92S","P97A","S83F","Q82W","Non-significant"))
  

supp_fig10<-supp_fig10_data%>%
  ggplot(aes(x=log2FC_PCA_score, y=log10p))+
  geom_hline(yintercept= -log10(0.05), linetype="dashed")+
  geom_point(aes(fill=mutation_sig, size=mutation_sig), shape=21)+
  geom_text_repel(data=supp_fig10_data%>%filter(mutation_sig != "Non-significant"), aes(label=partner, colour=mutation_sig), ylim=c(1.30103, NA), force=5, min.segment.length = 0.5, show.legend=F)+
  scale_y_continuous(expand=expansion(mult=c(0,0.25)))+
  scale_fill_manual(values = c(brewer.pal(8, name="Dark2"), "black"), limits=c("K85W", "I87W", "S83F", "Q82W", "P97A", "L98F", "N92H", "N92S", "Non-significant"))+
  scale_colour_manual(values = c(brewer.pal(8, name="Dark2"), "black"), limits=c("K85W", "I87W", "S83F", "Q82W", "P97A", "L98F", "N92H", "N92S", "Non-significant"))+
  scale_size_manual(values=c(rep(2, times=8), 1) , guide="none")+
  theme_classic()+
  theme_sup_figure()+
  theme(legend.background = element_rect(colour="black"),
        legend.box.margin=margin(l=1, unit="cm"),
        legend.position=c(0.1,0.35),
        legend.title = element_text(size=20),
        legend.text = element_text(size=17))+
  guides(fill=guide_legend(override.aes = list(size=3)))+
  labs(x="Log2FC interaction change compared to WT Pbs2",
       y="-log10(p-value)",
       fill="Mutant")

supp_fig10

save_plot(filename="./Supplementary_figure_10.png", plot = supp_fig10, dpi=300, base_height = 7.5)
  

rm(supp_fig10, supp_fig10_data)
```

```{r}
####Supp figure 11 - AF2 confidence metrics ####

#PANEL A

supp_11a_data<-read.csv("../../Data/AlphaFold_predictions/alphafold_output/PAE.csv")

supp_fig_11a<-supp_11a_data%>%
  ggplot(aes(x=scored_residue, y=aligned_residue, fill=PAE))+
  geom_tile()+
    scale_y_reverse(expand=c(0,0))+
    scale_x_continuous(expand=c(0,0))+
    scale_fill_gradient2(low="#022811", mid="#4BAF4D", high="#F8FDF6", breaks=c(0,5,10,15,20,25,30))+
    theme_sup_figure()+
    theme(
      # aspect.ratio = 1,
        panel.border = element_rect(colour="black", fill = NA),
        title = element_text(size=8),
        axis.text = element_text(colour="black"),
        strip.background=element_rect(fill=NA, colour=NA),
          strip.text = element_text(face="bold", size=10))+
  facet_wrap(~model, scales="free")+
    guides(fill=guide_colourbar(title.position = "top", 
                              frame.colour = "black", 
                              ticks.colour = "black", 
                              title.hjust =0.5))+
    labs(x="Scored residue",
         y="Aligned residue",
         fill="Expected position\nerror (Ångström)")

supp_fig_11a


#PANEL B

supp_11b_data<-read.csv("../../Data/AlphaFold_predictions/alphafold_output/pLDDT.csv")

models<-supp_11b_data%>%pull(model)%>%unique()
supp_11_sh3_domain<-data.frame(begin=c(302,0,302,302,302,302,302),
                      end=c(360,58,360,360,360,360,360),
                      model=models)
supp_11_extended_motif<-data.frame(begin=c(381,72,381,381,381,381,381),
                           end=c(397,88,397,397,397,397,397),
                           model=models)
supp_11_limit<-data.frame(value=c(367, 58,367,367,367,367,367),
                  model=models)

supp_fig_11b<-supp_11b_data%>%
  ggplot()+
    geom_rect(data=supp_11_extended_motif, ymin=-Inf, ymax=Inf, aes(xmin=begin, xmax=end),fill="skyblue")+
    geom_rect(data=supp_11_sh3_domain, aes(xmin=begin, xmax=end), ymin=-Inf, ymax=Inf, fill="#028b5b")+
    geom_line(aes(x=position, y = plddt))+
    geom_vline(data=supp_11_limit, aes(xintercept=value), linetype="dashed", colour="red", linewidth=0.75)+
    scale_x_continuous(expand=c(0,0))+
    facet_wrap(~model, scales="free_x")+
    theme_classic()+
    theme_sup_figure()+
    theme(strip.background=element_rect(fill=NA),
          strip.text = element_text(face="bold", size=10),)+
    labs(y="pLDDT", 
         x="Position in model")

supp_fig_11b


#ASSEMBLY

supp_fig_11<-plot_grid(supp_fig_11a,
                       NULL,
                       supp_fig_11b,
                       nrow=3, ncol=1,
                       rel_heights = c(1,0.05,1),
                       labels=c("a","", "b"), label_size = 20,
                       align="v",
                       axis="l")+theme(panel.background = element_rect("white", colour="white"))

supp_fig_11

save_plot(filename="./Supplementary_figure_11.png", plot=supp_fig_11, base_height=10, base_asp = 0.75, dpi=300)

```


```{r}
####Supp fig 12 - Structures####

supp_fig12a_H86W<-"../../Data/images/figS12_panel_a.png"
supp_fig12b_V91L<-"../../Data/images/figS12_panel_b.png"
supp_fig12c_V91M<-"../../Data/images/figS12_panel_c.png"
supp_fig12d_Q89D<-"../../Data/images/figS12_panel_d.png"

supp_fig12a_panel_H86W<-ggdraw()+draw_image(supp_fig12a_H86W, scale=1)
supp_fig12b_panel_V91L<-ggdraw()+draw_image(supp_fig12b_V91L, scale=1)
supp_fig12c_panel_V91M<-ggdraw()+draw_image(supp_fig12c_V91M, scale=1)
supp_fig12d_panel_Q89D<-ggdraw()+draw_image(supp_fig12d_Q89D, scale=1)


supp_fig12<-plot_grid(supp_fig12a_panel_H86W,
                      supp_fig12b_panel_V91L,
                      supp_fig12c_panel_V91M,
                      supp_fig12d_panel_Q89D,
                     labels = "auto", label_colour="black", label_x = 0, label_y = 1.05, label_size = 12,
                     nrow = 2, ncol = 2)+
  theme(panel.background=element_rect(fill="white", colour="white"))

supp_fig12


save_plot("./Supplementary_figure_12.png", supp_fig12, ncol=2, nrow=2, dpi=500, base_height=1)

rm(supp_fig12, supp_fig12a_panel_H86W, supp_fig12b_panel_V91L, supp_fig12c_panel_V91M, supp_fig12d_panel_Q89D, supp_fig12a_H86W, supp_fig12b_V91L, supp_fig12c_V91M, supp_fig12d_Q89D)

```

