
```{r, Chunk 1, warning =FALSE, message =FALSE}
#### Chunk 1 : Load packages####
library(tidyr)
library(ggplot2)
library(stringr)
library(magrittr)
library(dplyr)
library(purrr)
library(rstatix)

```


```{r}
####Chunk 2: Import and export info####

###Input files
#Files with info about colonies
info<-read.csv("../../Data/Solid_PCA/design/plate_info.csv")
partners<-read.csv("../../Data/Solid_PCA/design/quadrant_partners.csv")
strain_legend<-"../../Data/Solid_PCA/design/legend_strains_for_array.xlsx"
#Colony size folders
preselection_folder<-"../../Data/Solid_PCA/colony_sizes/pre_selection_colony_sizes/"
postselection_folder<-"../../Data/Solid_PCA/colony_sizes/post_selection_colony_sizes/"
#Files with results from other experiments
validation_file<-"../../Data/DMS/results/aa_validation_scores.csv"
surrounding_region_scan_results_path<-"../../Data/DMS/results/aa_surrounding_region_DMS_scores.csv"

#Output_files
output_file <- "../../Data/Solid_PCA/results/solid_pca_results.csv"


```


```{r}

####Chunk 3: Import colony sizes####

#Import each of the plates final timepoints and combine into one dataframe

df<-data.frame(row=rep(1:32, each=48), column=rep(1:48, times=32))
for(i in 1:nrow(info)){
  if (i %% 5 == 0) {print(i)}
  file<-paste0(postselection_folder,info[i, "file"])
  r<- read.csv(file, check.names = F) %>% 
    dplyr::rename(timepoint = 1) %>%
    pivot_longer(cols = -timepoint, names_to = "position", values_to = paste(i)) %>%
               separate(col=position, into = c("row", "column"), sep="-", convert=T) %>% 
               filter(timepoint==48) %>%                                                  #Only take final timepoint
               dplyr::select(-timepoint) 
                
  df<-left_join(df, r, by=c("row", "column"))
}

#Transfer to long format
df <- pivot_longer(df, cols = -c(row, column), names_to = "plate", values_to = "area", names_transform = list(plate= as.integer))

#Add the information to each mutant which is contained in csv files 
df<- left_join(df, info, by="plate")
df<-left_join(df, partners, by=c("column", "row", "target")) %>%
  dplyr::rename(partner = Gene)

#Only keep the appropriate strain for each colony
df <- df %>%
  mutate(mutant = case_when( q == "A" ~ qA.strain,
                             q == "B" ~ qB.strain,
                             q == "C" ~ qC.strain,
                             q == "D" ~ qD.strain)) %>%
  dplyr::select(-c(qA.strain, qB.strain, qC.strain, qD.strain, original_column, original_row))

#Import information about which strain is which precise mutation
mutant_def<-readxl::read_xlsx(strain_legend, col_names = c("mutant", "mutation")) %>% 
  mutate(mutant = str_remove_all(mutant, pattern = "DJ_"))


#Add mutant information to dataframe
df <- left_join(df, mutant_def, by="mutant")


rm(mutant_def, r, i, file)
```


```{r}

####Chunk 4: Import mated colony sizes####

#Now import the information about the colonies before selection, to remove any colonies which were not present before selection, but appear afterwards, as these may be contamination

#Import the 
pre_sel<-data.frame()
for(i in 1:nrow(info)){
  if (i %% 5 == 0) {print(i)}
 file<- paste0(preselection_folder, info[i, "pre_selection_file"])
r<-read.csv(file, check.names = F) %>%
  dplyr::select(c(area, row, column)) %>%
  mutate(plate = i, condition = info[i, "Condition"])

pre_sel<- rbind(pre_sel, r)
}

#The positions missing from this S2 dataframe should not be in the MTX (final) dataframe, if they are present that is a mistake. I can therefore take the missing rows from S2 out of final

#This identifies the positions and plates
not_in_presel<-setdiff(dplyr::select(df, c(row, column, plate)), dplyr::select(pre_sel, c(row, column, plate)))
#This pulls out the appropriate rows in the df
not_in_presel<-semi_join(df, not_in_presel, by=c("plate", "row", "column"))
#Remove the borders (which will be taken out anyways) and those that are NA (if colony didn't grow at pre_selection, then should Na after selection, so no need to take into account)
not_in_presel<-filter(not_in_presel, row %in% 2:31 & column %in% 2:47 & !is.na(area))



#Only two colonies are not NA (which are going to be removed anyways), or in the border (which I don't want to remove so that I can do normalization). I manually checked the pictures for these two colonies, and they seem to be mistakes. I will remove them manually

df[df$plate == 19 & df$row == 28 & df$column == 33, "area"] <- NA
df[df$plate == 10 & df$row == 9 & df$column == 26, "area"] <- NA


rm(pre_sel, r, not_in_presel, i, file)

```


```{r}

####Chunk 5: Normalize colony sizes####

#Now normalize the colony sizes to the background. This part is based on Ugo's script, available on GitHub https://github.com/Landrylab/DionneEtal2020/blob/master/FirstPCAScreen_DionneEtal2020.R



# Log2 transformation of colony size and remove positions with no growth in the DHFR-PCA selection.
df %<>% mutate(adjusted_area = area+1)
df %<>% mutate(log2 = log2(adjusted_area))
df <- subset(df, df$log2 > 2) 

#distribution before normalization to plate background
# ggplot(df, aes(x=log2, colour=condition, group=plate))+
#   geom_density()+
#   theme_bw()+
#   ggtitle("Distribution before normalization")
# 
# #Is there a bias introduced by the position in the array?
# df%>%
#   ggplot(aes(x=log2, y=as.factor(plate), colour=condition))+
#   geom_boxplot()+
#   labs("is there bias from plate")
# 
# df%>%
#   ggplot(aes(x=as.factor(column), y=log2, colour=condition))+
#   geom_boxplot()+
#   facet_wrap(~plate)+
#   labs("Is there bias from position in column")
# 
# df%>%
#   ggplot(aes(x=log2, y=as.factor(row), colour=condition))+
#   geom_boxplot()+
#   facet_wrap(~plate)+
#   labs("Is there bias from position in row")

#Normalize by row
df%<>%
  filter(partner!="blank")%>%
  group_by(plate, row)%>%
  summarize(row_med=median(log2, na.rm=T))%>%
  ungroup()%>%
  right_join(., df, by=c("plate", "row"))%>%
  mutate(row_norm=log2-row_med)

#Normalize by column
df%<>%
  filter(partner!="blank")%>%
  group_by(plate, column)%>%
  summarize(col_med=median(row_norm, na.rm=T))%>%
  ungroup()%>%
  right_join(., df, by=c("plate", "column"))%>%
  mutate(col_norm=row_norm-col_med)

# Normalize the colony size to plate background
df %<>% 
  group_by(plate) %>%
  mutate(platemed = median(col_norm, na.rm=T)) %>%
  ungroup()
df%<>% mutate(mednorm=col_norm-platemed)


#Check that normalization worked

ggplot(df, aes(x=mednorm, colour=condition, group=plate))+
  geom_density()+
  theme_bw()+
  ggtitle("Normalized PCA scores")

ggplot(df,aes(x=mednorm, y=as.factor(plate), colour=condition))+
  geom_boxplot()+
  theme_bw()+
  ggtitle("Normalized PCA score by plate")


#Is there still a bias introduced by the position in the array?
# df%>%
#   ggplot(aes(x=mednorm, y=as.factor(plate), colour=condition))+
#   geom_boxplot()+
#   labs("is there bias from plate")
# 
# df%>%
#   ggplot(aes(x=as.factor(column), y=mednorm, colour=condition))+
#   geom_boxplot()+
#   facet_wrap(~plate)+
#   labs("Is there bias from position in column")
# 
# df%>%
#   ggplot(aes(x=mednorm, y=as.factor(row), colour=condition))+
#   geom_boxplot()+
#   facet_wrap(~plate)+
#   labs("Is there bias from position in row")
```

```{r}
####CHUNK 6: Filter values####

interactions_to_keep<-c("LSB1_DHFR[12]",
                        "BOI2_DHFR[12]",
                        "RVS167_DHFR[12]",
                        "HSE1_DHFR[12]",
                        "NBP2_DHFR[12]",
                        "CDC25_DHFR[12]",
                        "BZZ1_DHFR[12]",
                        "ABP1_DHFR[12]",
                        "PIN3_DHFR[12]",
                        "LSB3_DHFR[12]",
                        "CYK3_DHFR[12]",
                        "SLA1_DHFR[12]",
                        "SHO1_STUFFED_DHFR[12]",
                        "BEM1_DHFR[12]",
                        "PEX13_DHFR[12]",
                        "FUS1_DHFR[12]",
                        "HOF1_DHFR[12]",
                        "BOI1_DHFR[12]",
                        "SDC25_17W_DHFR[12]",
                        "SHO1_DHFR[12]",
                        "YSC84_DHFR[12]",
                        "MYO3_DHFR[12]",
                        "BBC1_DHFR[12]",
                        "BUD14_DHFR[12]",
                        "MYO5_DHFR[12]")



df%<>%
  filter(partner %in% interactions_to_keep)%>%
  mutate(partner = str_remove(partner, "_DHFR\\[12\\]"))%>%
  filter(mutation %in% c("WT", "stuffed"))

```





```{r}

####CHUNK 7: Rescale and Visualize interactions####

Sho1_wt_median<-df%>%
  filter(condition == "MTX" & partner == "SHO1" & mutation == "WT")%>%
  pull(mednorm)%>%
  median()
  
Sho1_stuffed_median<-df%>%
  filter(condition == "MTX" & partner == "SHO1" & mutation == "stuffed")%>%
  pull(mednorm)%>%
  median()

rescaled_df<-df%>%
  mutate(mednorm=(mednorm-Sho1_stuffed_median)/(Sho1_wt_median-Sho1_stuffed_median))

rescaled_df%>%
  ggplot(aes(x=partner, y=mednorm))+
  geom_boxplot(outlier.shape=NA, aes(fill=mutation))+
  geom_point(position = position_jitterdodge(jitter.width = 0.35), aes(fill=mutation), colour="black", shape=21)+
  facet_wrap(~condition)+
  theme(axis.text.x = element_text(angle=45, hjust=1, vjust=1))


sig_test<-rescaled_df%>%
  group_by(mutation, condition)%>%
rstatix::pairwise_wilcox_test(formula= mednorm ~ partner,
                              ref.group = "SHO1",
                              p.adjust.method = "fdr",
                              alternative = "greater")

#All interactions except Abp1-WT Pbs2 and Nbp2-WT Pbs2 are significantly weaker than Sho1-WT Pbs2 (One sided Mann-Whitney U test  with fdr corrected p-value < 0.05)

```




```{r}

####CHUNK 8 : EXPORT VALUES FOR MUTANTS ####

write.csv(rescaled_df, output_file, row.names=F)

``` 

