

```{r}
library(cowplot)
library(ggplot2)

```

```{r}
#PANEL A - POSITION MINUS 9

#Read images
pbs2_9<-"../Data/images/Fig5/annotations_Pbs2_9.png"
ark1_9_contacts<-"../Data/images/Fig5/annotations_Ark1_9.png"
ste20_nbp2_9_contacts<-"../Data/images/Fig5/annotations_nbp2_9.png"
ste20_bem1_9_contacts<-"../Data/images/Fig5/annotations_bem1_9.png"


#Draw images as gg objects
pic_pbs2_9<-ggdraw()+draw_image(pbs2_9, scale=1)
pic_ark1_9_contacts<-ggdraw()+draw_image(ark1_9_contacts, scale=1)
pic_ste20_nbp2_9_contacts<-ggdraw()+draw_image(ste20_nbp2_9_contacts, scale=1)
pic_ste20_bem1_9_contacts<-ggdraw()+draw_image(ste20_bem1_9_contacts, scale=1)

#Assemble and annotate images
position_minus_9<-plot_grid(pic_pbs2_9,
          pic_ark1_9_contacts,
          pic_ste20_nbp2_9_contacts,
          pic_ste20_bem1_9_contacts)+
  annotate(geom="label", x=c(0.1,0.6,0.1,0.6), y=c(0.9,0.9,0.4,0.4), label=c("Sho1-Pbs2", "Abp1-Ark1", "Nbp2-Ste20", "Bem1-Ste20"), colour="black", size=5)

#Save panel
save_plot(filename = "../Data/images/Fig5/position_minus_9_assembled.png", plot=position_minus_9, bg="white")


```

```{r}
#PANEL B - POSITION MINUS 6

#Read images
pbs2_6<-"../Data/images/Fig5/annotations_Pbs2_6.png"
ark1_6_contacts<-"../Data/images/Fig5/annotations_Ark1_6.png"
ste20_nbp2_6_contacts<-"../Data/images/Fig5/annotations_nbp2_6.png"
ste20_bem1_6_contacts<-"../Data/images/Fig5/annotations_bem1_6.png"


#Draw images as gg objects
pic_pbs2_6<-ggdraw()+draw_image(pbs2_6, scale=1)
pic_ark1_6_contacts<-ggdraw()+draw_image(ark1_6_contacts, scale=1)
pic_ste20_nbp2_6_contacts<-ggdraw()+draw_image(ste20_nbp2_6_contacts, scale=1)
pic_ste20_bem1_6_contacts<-ggdraw()+draw_image(ste20_bem1_6_contacts, scale=1)

#Assemble and annotate images
position_minus_6<-plot_grid(pic_pbs2_6,
          pic_ark1_6_contacts,
          pic_ste20_nbp2_6_contacts,
          pic_ste20_bem1_6_contacts)+
  annotate(geom="label", x=c(0.1,0.6,0.1,0.6), y=c(0.9,0.9,0.4,0.1), label=c("Sho1-Pbs2", "Abp1-Ark1", "Nbp2-Ste20", "Bem1-Ste20"), colour="black", size=5)

#Save panel
save_plot(filename = "../Data/images/Fig5/position_minus_6_assembled.png", plot=position_minus_6, bg="white")

```

```{r}
#ASSEMBLY

fig_5<-plot_grid(position_minus_9,
                 ggplot()+theme_classic(), #extra spacing between panels
                 position_minus_6,
                 labels=c("a", "", "b"), label_size = 30, label_y =1.01 ,
                 nrow=3, ncol=1,
                 rel_heights = c(1,0.05,1)
                 )


save_plot(filename = "../Data/images/Fig5/fig_5.png", plot = fig_5, ncol=1, nrow=3, bg="white", base_asp = 2.2)


```




